mytyple=("Navoiy","Samarqand", "Buxoro","Xorazm","Qoraqalpog'iston Respublikasi")
# x=mytyple.index("Navoiy")
# print(x)
y=list(mytyple)
y.append("Jizzax")
print(y)
x=tuple(y)
print(x)
print(type(x))
print(type(y))
